export const contectInfo = {
  ShopName: "SHREE BAIDYANATH TRADING",
  mobile: "8880317459",
  whatsappNumber: "8880317459",
  shop_location:
    "Sree baidyanath trading, infront of petrol pump, Baghmara shi nagar road near sharashwati vidya mandir, Purnia, Bihar 854301",
  shop_location_link:
    "https://www.google.com/maps/place/Sree+baidyanath+trading/@25.8044977,87.4780577,17z/data=!4m10!1m2!2m1!1sSree+baidyanath+trading,+infront+of+petrol+pump,+Baghmara+shi+nagar+road+near+sharashwati+vidya+mandir,+Purnia,+Bihar+854301!3m6!1s0x39eff9da8c063b5f:0xf1463c1d1e003008!8m2!3d25.8048139!4d87.4802908!15sCnlTcmVlIGJhaWR5YW5hdGggdHJhZGluZywgaW5mcm9udCBvZiBwZXRyb2wgcHVtcCwgQmFnaG1hcmEgc3JpbmFnYXIgcm9hZCBuZWFyIHNhcmFzd2F0aSB2aWR5YSBtYW5kaXIsIFB1cm5pYSwgQmloYXIgODU0MzAxWncidXNyZWUgYmFpZHlhbmF0aCB0cmFkaW5nIGluZnJvbnQgb2YgcGV0cm9sIHB1bXAgYmFnaG1hcmEgc3JpbmFnYXIgcm9hZCBuZWFyIHNhcmFzd2F0aSB2aWR5YSBtYW5kaXIgcHVybmlhIGJpaGFyIDg1NDMwMZIBGGJ1aWxkaW5nX21hdGVyaWFsc19zdG9yZeABAA!16s%2Fg%2F11p02qkx33?entry=ttu",

  godName: "OM NAMAH SHIVAYA",
};

export const materialsData = {
  HotDeal: [
    {
      image: "/images/Materials/Bricks/greenStonebrick_image.png",
      materialName: "Greenstone's AAC Brick - 600mmX200mmX100mm (4'')",
      materialMrp: 40.0,
      isSalePrice: true,
      inStock: true,
      materialSalePrice: 38.0,
      materialCount: "per Nos",
      discount: "UPTO 5% OFF",
      materialManufacturedby: "by Greenstone",
    },
    {
      image: "/images/Materials/Bricks/AccBricks.jpg",
      materialName: "Aerobild - 600 x 200 x 230(9'')",
      materialMrp: 135.0,
      isSalePrice: true,
      inStock: false,
      materialSalePrice: 96.0,
      materialCount: "per Piece",
      discount: "UPTO 28% OFF",
      materialManufacturedby: "by Aerobild",
    },
    {
      image: "/images/Materials/Rod/sugnarod.jpg",
      materialName: "Sugna TMT Fe-550 Grade - 16mm",
      materialMrp: "92,115.00",
      isSalePrice: false,
      inStock: true,
      materialSalePrice: 96.0,
      materialCount: "per Kg",
      discount: "UPTO 28% OFF",
      materialManufacturedby: "by Sugna-TMT",
    },
    {
      image: "/images/Materials/Rod/bindingWire.jpg",
      materialName: "Binding Wire",
      materialMrp: "115.00",
      isSalePrice: true,
      inStock: false,
      materialSalePrice: 100.0,
      materialCount: "per Kg",
      discount: "UPTO 13% OFF",
      materialManufacturedby: "Binding Wire",
    },
    {
      image: "/images/Materials/Bricks/RedBrick.jpg",
      materialName: "Local Red Brick - 8-10 x 3.8 x 2.9",
      materialMrp: "14.00",
      isSalePrice: true,
      inStock: true,
      materialSalePrice: 12.0,
      materialCount: "per Piece",
      discount: "UPTO 14% OFF",
      materialManufacturedby: "By Karnataka Red Bricks",
    },
    {
      image: "/images/Materials/Cement/BirlaStrongCreteCement.png",
      materialName: "Birla.A1 StrongCrete",
      materialMrp: "470.00",
      isSalePrice: false,
      inStock: true,
      materialSalePrice: 12.0,
      materialCount: "per Bag",
      discount: "UPTO 14% OFF",
      materialManufacturedby: "by Birla A1",
    },
    {
      image: "/images/Materials/Cement/AccCement.png",
      materialName: "ACC Suraksha Cement",
      materialMrp: "480.00",
      isSalePrice: false,
      inStock: false,
      materialSalePrice: 12.0,
      materialCount: "per Bag",
      discount: "UPTO 14% OFF",
      materialManufacturedby: "by Acc Cement",
    },
  ],

  Cement: [
    {
      image: "/images/Materials/Cement/BirlaStrongCreteCement.png",
      materialName: "Birla.A1 StrongCrete",
      materialMrp: "470.00",
      isSalePrice: false,
      inStock: true,
      materialSalePrice: 12.0,
      materialCount: "per Bag",
      discount: "UPTO 14% OFF",
      materialManufacturedby: "by Birla A1",
    },
    {
      image: "/images/Materials/Cement/AccCement.png",
      materialName: "ACC Suraksha Cement",
      materialMrp: "480.00",
      isSalePrice: false,
      inStock: false,
      materialSalePrice: 12.0,
      materialCount: "per Bag",
      discount: "UPTO 14% OFF",
      materialManufacturedby: "by Acc Cement",
    },
    {
      image: "/images/Materials/Cement/bangur2.jpg",
      materialName: "Bangur PPC Cement",
      materialMrp: "480.00",
      isSalePrice: true,
      inStock: true,
      materialSalePrice: 315.0,
      materialCount: "per Bag",
      discount: "UPTO 12% OFF",
      materialManufacturedby: "by Bangur",
    },
    {
      image: "/images/Materials/Cement/bangur1.jpg",
      materialName: "Bangur OPC Cement",
      materialMrp: "480.00",
      isSalePrice: true,
      inStock: true,
      materialSalePrice: 335.0,
      materialCount: "per Bag",
      discount: "UPTO 12% OFF",
      materialManufacturedby: "by Bangur",
    },
    {
      image: "/images/Materials/Cement/ACCConcretePlus.png",
      materialName: "ACC Concrete Plus - 53Grade",
      materialMrp: "500.00",
      isSalePrice: true,
      inStock: true,
      materialSalePrice: 480,
      materialCount: "per Bag",
      discount: "UPTO 4% OFF",
      materialManufacturedby: "by Acc Cement",
    },
    {
      image: "/images/Materials/Cement/ambuja_ppcCement.jpg",
      materialName: "Ambuja PPC Cement",
      materialMrp: "430.00",
      isSalePrice: true,
      inStock: true,
      materialSalePrice: 340.0,
      materialCount: "per Bag",
      discount: "UPTO 20% OFF",
      materialManufacturedby: "by Ambuja Cement",
    },
    {
      image: "/images/Materials/Cement/BHAVYACemet.jpg",
      materialName: "BHAVYACemet",
      materialMrp: "350.00",
      isSalePrice: false,
      inStock: true,
      materialSalePrice: 340.0,
      materialCount: "per Bag",
      discount: "UPTO 20% OFF",
      materialManufacturedby: "by Bhavya Cement",
    },

    {
      image: "/images/Materials/Cement/BirlaStrongCreteCement.png",
      materialName: "Birla.A1 StrongCrete",
      materialMrp: "470.00",
      isSalePrice: false,
      inStock: true,
      materialSalePrice: 12.0,
      materialCount: "per Bag",
      discount: "UPTO 14% OFF",
      materialManufacturedby: "by Birla A1",
    },
    {
      image: "/images/Materials/Cement/AccCement.png",
      materialName: "ACC Suraksha Cement",
      materialMrp: "480.00",
      isSalePrice: false,
      inStock: false,
      materialSalePrice: 12.0,
      materialCount: "per Bag",
      discount: "UPTO 14% OFF",
      materialManufacturedby: "by Acc Cement",
    },
    {
      image: "/images/Materials/Cement/bangur2.jpg",
      materialName: "Bangur PPC Cement",
      materialMrp: "480.00",
      isSalePrice: true,
      inStock: true,
      materialSalePrice: 315.0,
      materialCount: "per Bag",
      discount: "UPTO 12% OFF",
      materialManufacturedby: "by Bangur",
    },
    {
      image: "/images/Materials/Cement/bangur1.jpg",
      materialName: "Bangur OPC Cement",
      materialMrp: "480.00",
      isSalePrice: true,
      inStock: true,
      materialSalePrice: 335.0,
      materialCount: "per Bag",
      discount: "UPTO 12% OFF",
      materialManufacturedby: "by Bangur",
    },
    {
      image: "/images/Materials/Cement/ACCConcretePlus.png",
      materialName: "ACC Concrete Plus - 53Grade",
      materialMrp: "500.00",
      isSalePrice: true,
      inStock: true,
      materialSalePrice: 480,
      materialCount: "per Bag",
      discount: "UPTO 4% OFF",
      materialManufacturedby: "by Acc Cement",
    },
    {
      image: "/images/Materials/Cement/ambuja_ppcCement.jpg",
      materialName: "Ambuja PPC Cement",
      materialMrp: "430.00",
      isSalePrice: true,
      inStock: true,
      materialSalePrice: 340.0,
      materialCount: "per Bag",
      discount: "UPTO 20% OFF",
      materialManufacturedby: "by Ambuja Cement",
    },
    {
      image: "/images/Materials/Cement/BHAVYACemet.jpg",
      materialName: "BHAVYACemet",
      materialMrp: "350.00",
      isSalePrice: false,
      inStock: true,
      materialSalePrice: 340.0,
      materialCount: "per Bag",
      discount: "UPTO 20% OFF",
      materialManufacturedby: "by Bhavya Cement",
    },
  ],
  Paints: [
    {
      image: "images/Materials/Paints/nerolacBeautyGold.webp",
      materialName:
        "nerolac Beauty Gold Premium Emulsion 4ltr White White Emulsion Wall Paint",
      materialMrp: "2153.00",
      isSalePrice: true,
      inStock: true,
      materialSalePrice: 1910.0,
      materialCount: "per Tin",
      discount: "UPTO 14% OFF",
      materialManufacturedby: "by Nerolac Paints",
    },
    {
      image: "images/Materials/Paints/nerolacgoldwashable.webp",
      materialName:
        "nerolac Beauty Gold Washable Premium Emulsion 20ltr White Emulsion Wall Paint ",
      materialMrp: "11500.00",
      isSalePrice: true,
      inStock: true,
      materialSalePrice: 9800.0,
      materialCount: "per Tin",
      discount: "UPTO 14% OFF",
      materialManufacturedby: "by Nerolac Paints",
    },
    {
      image: "images/Materials/Paints/nerolacBeautyGold.webp",
      materialName:
        "nerolac Beauty Gold Premium Emulsion 20ltr White White Emulsion Wall Paint",
      materialMrp: "8500.00",
      isSalePrice: true,
      inStock: true,
      materialSalePrice: 7999.0,
      materialCount: "per Tin",
      discount: "UPTO 14% OFF",
      materialManufacturedby: "by Nerolac Paints",
    },
    {
      image: "images/Materials/Paints/nerolacUltimateExterior.webp",
      materialName:
        "nerolac Excel Everlast 12 White Ulimate Exterior Paint 20ltr White White Emulsion Wall Paint",
      materialMrp: "17600.00",
      isSalePrice: true,
      inStock: true,
      materialSalePrice: 14500.0,
      materialCount: "per Tin",
      discount: "UPTO 14% OFF",
      materialManufacturedby: "by Nerolac Paints",
    },
    {
      image: "images/Materials/Paints/nerolacImpression.webp",
      materialName:
        "nerolac Impression HD 24 Carat Premium Emulsion 4 ltr White Emulsion Wall Paint",
      materialMrp: "3584.00",
      isSalePrice: true,
      inStock: true,
      materialSalePrice: 3304.0,
      materialCount: "per Tin",
      discount: "UPTO 14% OFF",
      materialManufacturedby: "by Nerolac Paints",
    },
    {
      image: "images/Materials/Paints/nerolacExcelMica.webp",
      materialName:
        "nerolac Excel Mica Marble Stretch and Sheen White Exterior Paint 4ltr White Emulsion Wall Paint ",
      materialMrp: "2580.00",
      isSalePrice: true,
      inStock: true,
      materialSalePrice: 2451.0,
      materialCount: "per Tin",
      discount: "UPTO 14% OFF",
      materialManufacturedby: "by Nerolac Paints",
    },
    {
      image: "images/Materials/Paints/nerolacUltimateExterior.webp",
      materialName:
        "nerolac Excel Everlast 12 White Ulimate Exterior Paint 4ltr White Emulsion Wall Paint",
      materialMrp: "3864.00",
      isSalePrice: true,
      inStock: true,
      materialSalePrice: 3570.0,
      materialCount: "per Tin",
      discount: "UPTO 14% OFF",
      materialManufacturedby: "by Nerolac Paints",
    },
    {
      image: "images/Materials/Paints/nerolacgoldwashable.webp",
      materialName:
        "nerolac Beauty Gold Washable Premium Emulsion 20ltr White Emulsion Wall Paint ",
      materialMrp: "11500.00",
      isSalePrice: true,
      inStock: true,
      materialSalePrice: 9800.0,
      materialCount: "per Tin",
      discount: "UPTO 14% OFF",
      materialManufacturedby: "by Nerolac Paints",
    },
  ],
  Bricks: [
    {
      image: "images/Materials/Bricks/ConcreteSolidBlocks.png",
      materialName:
        "KSP Eco Brick - 4''(4inch x 8inch x 16inch) (100mm x 200mm x 400mm)",
      materialMrp: "47.00",
      isSalePrice: true,
      inStock: true,
      materialSalePrice: 39.0,
      materialCount: "per Nos",
      discount: "UPTO 17% OFF",
      materialManufacturedby: "by KSP Eco Bricks",
    },
    {
      image: "images/Materials/Bricks/ConcreteSolidBlocks.png",
      materialName:
        "KSP Eco Brick - 8''(8inch x 8inch x 12inch) (200mm x 200mm x 300mm)",
      materialMrp: "57.00",
      isSalePrice: false,
      inStock: true,
      materialSalePrice: 39.0,
      materialCount: "per Nos",
      discount: "UPTO 17% OFF",
      materialManufacturedby: "by KSP Eco Bricks",
    },
    {
      image: "images/Materials/Bricks/ConcreteSolidBlocks.png",
      materialName:
        "KSP Eco Brick - 6''(6inch x 8inch x 12inch) (150mm x 200mm x 300mm)",
      materialMrp: "42.04",
      isSalePrice: true,
      inStock: true,
      materialSalePrice: 39.0,
      materialCount: "per Nos",
      discount: "UPTO 12% OFF",
      materialManufacturedby: "by KSP Eco Bricks",
    },
    {
      image: "images/Materials/Bricks/ConcreteSolidBlocks.png",
      materialName:
        "KSP Eco Block - 4''(4inch x 6inch x 12inch) (100mm x 140mm x 290mm)",
      materialMrp: "25.53",
      isSalePrice: false,
      inStock: true,
      materialSalePrice: 39.0,
      materialCount: "per Nos",
      discount: "UPTO 17% OFF",
      materialManufacturedby: "by KSP Eco Bricks",
    },
    {
      image: "images/Materials/Bricks/d_lite_light_weight_bricks.jpg",
      materialName: "D Lite CLC Block",
      materialMrp: "38.00",
      isSalePrice: false,
      inStock: true,
      materialSalePrice: 39.0,
      materialCount: "per Nos",
      discount: "UPTO 17% OFF",
      materialManufacturedby: "by KSP Eco Bricks",
    },
    {
      image: "images/Materials/Bricks/bbcnsbksp0003.png",
      materialName:
        "KSP Eco Brick - 6''(9inch x 3inch x 6inch) (230mm X 70mm X 154mm)",
      materialMrp: "12.0",
      isSalePrice: false,
      inStock: true,
      materialSalePrice: 39.0,
      materialCount: "per Nos",
      discount: "UPTO 17% OFF",
      materialManufacturedby: "by KSP Eco Bricks",
    },
    {
      image: "images/Materials/Bricks/ConcreteSolidBlocks.png",
      materialName:
        "KSP Eco Brick - 4''(4inch x 8inch x 16inch) (100mm x 200mm x 400mm)",
      aterialMrp: "47.00",
      isSalePrice: false,
      inStock: true,
      materialSalePrice: 39.0,
      materialCount: "per Nos",
      discount: "UPTO 17% OFF",
      materialManufacturedby: "by KSP Eco Bricks",
    },
    {
      image: "images/Materials/Bricks/d_lite_light_weight_bricks.jpg",
      materialName:
        "KSP Eco Brick - 9''(9inch x 3inch x 4inch) (230mm X 70mm X 110mm)",
      materialMrp: "13.14",
      isSalePrice: true,
      inStock: true,
      materialSalePrice: 10.0,
      materialCount: "per Nos",
      discount: "UPTO 23% OFF",
      materialManufacturedby: "by KSP Eco Bricks",
    },
    {
      image: "images/Materials/Bricks/bbcnsbksp0003.png",
      materialName:
        "KSP Eco Brick - 6''(9inch x 3inch x 6inch) (230mm X 70mm X 154mm)",
      materialMrp: "12.0",
      isSalePrice: false,
      inStock: true,
      materialSalePrice: 39.0,
      materialCount: "per Nos",
      discount: "UPTO 17% OFF",
      materialManufacturedby: "by KSP Eco Bricks",
    },
  ],
  Rods: [],
};

export const Feedback = [
  {
    imageUrl: "/images/shraddha.jpg",
    name: "Shraddha Kapoor",
    Rating: 5,
    review:
      "Your shop's hospitality exceeded my expectations! From the warm greetings to the attentive service, every moment was a delight. Thank you for creating such a welcoming atmosphere. I look forward to visiting again soon!",
    date: "09 Feb 2024",
  },
  {
    imageUrl: "/images/rockybai.jpg",
    name: "Rocky Bhai",
    Rating: 4.5,
    review:
      "I couldn't be more impressed with the hospitality at your shop! The staff went above and beyond to ensure my experience was nothing short of exceptional. From their knowledge of the products to their genuine friendliness, every interaction was a pleasure. Thank you for making me feel like a valued customer!",
    date: "01 Feb 2024",
  },
  {
    imageUrl: "/images/kiara.jpg",
    name: "Kiara advani",
    Rating: 5,
    review:
      "What a wonderful experience! Your shop's hospitality truly sets a standard. From the moment I walked in, I felt welcomed and appreciated. The attention to detail and personalized service made my visit memorable. I'll definitely be recommending your shop to friends and family!",
    date: "25 Jan 2024",
  },
  {
    imageUrl: "/images/sidharth.jpg",
    name: "Sidharth Malhotra",
    Rating: 5,
    review:
      "I wanted to express my gratitude for the incredible hospitality I received during my recent visit to your shop. The staff's warmth and professionalism made me feel right at home. It's evident that customer satisfaction is a top priority here. Keep up the fantastic work, and I'll definitely be back for more!",
    date: "15 Jan 2024",
  },
  {
    imageUrl: "/images/shraddha.jpg",
    name: "Shraddha Kapoor",
    Rating: 5,
    review:
      "Your shop's hospitality exceeded my expectations! From the warm greetings to the attentive service, every moment was a delight. Thank you for creating such a welcoming atmosphere. I look forward to visiting again soon!",
    date: "09 Feb 2024",
  },
];

export const materialBrands = {
  Cement: [
    {
      imageUrl: "/images/Materials/Cement/Ultra-Tech-Logo.jpg",
      name: "UltraTech Cement",
    },
    {
      imageUrl: "/images/Materials/Cement/accCementlogo.jpg",
      name: "Acc Cement",
    },
    {
      imageUrl: "/images/Materials/Cement/bangerLogo.png",
      name: "Banger Cement",
    },
    {
      imageUrl: "/images/Materials/Cement/nuvoco-vistas-logo.png",
      name: "Nuvoco Cement",
    },
    {
      imageUrl: "/images/Materials/Cement/concretoLogo.png",
      name: "Concreto Cement",
    },
  ],
  Rods: [
    {
      imageUrl: "/images/Materials/Rod/tatatisconlogo.jpg",
      name: "Tata Tiscon Rod",
    },
    {
      imageUrl: "/images/Materials/Rod/balmukundlogo.jpg",
      name: "BalMukund Rod",
    },
    {
      imageUrl: "/images/Materials/Rod/durgapurlogo.jpg",
      name: "Durgapur Rod",
    },
    {
      imageUrl: "/images/Materials/Rod/magadhlogo.jpg",
      name: "Magadh Rod",
    },
  ],
  Bricks: [
    {
      imageUrl: "images/Materials/Bricks/ConcreteSolidBlocks.png",
      name: "Concrete Blocks",
    },
    {
      imageUrl: "images/Materials/Bricks/d_lite_light_weight_bricks.jpg",
      name: "D Lite CLC Block",
    },
  ],
  Paints: [
    {
      imageUrl: "/images/Materials/Paints/nerolacLogo.png",
      name: "Nerolac Paint",
    },
    {
      imageUrl: "/images/Materials/Paints/nerolacLogo.png",
      name: "Nerolac Paint",
    },
  ],
};
